[KUBEGALE]2025-05-17 11:36:26.268	[31merror[0m	/Users/daihao/Downloads/gocode/KubeGale/utils/claims.go:48	重新写入cookie token失败,未能成功解析token,请检查请求头是否存在x-token且claims是否为规定结构
[KUBEGALE]2025-05-17 14:34:28.945	[31merror[0m	/Users/daihao/Downloads/gocode/KubeGale/service/im/card_content.go:27	查询通知配置失败	{"notification_id": 1, "error": "record not found"}
[KUBEGALE]2025-05-17 14:34:28.948	[31merror[0m	/Users/daihao/Downloads/gocode/KubeGale/api/v1/im/notification.go:223	创建卡片内容失败	{"error": "通知配置不存在"}
[KUBEGALE]2025-05-17 14:36:42.910	[31merror[0m	/Users/daihao/Downloads/gocode/KubeGale/core/server.go:68	accept tcp [::]:8080: use of closed network connection
[KUBEGALE]2025-05-17 14:39:28.793	[31merror[0m	/Users/daihao/Downloads/gocode/KubeGale/utils/claims.go:48	重新写入cookie token失败,未能成功解析token,请检查请求头是否存在x-token且claims是否为规定结构
[KUBEGALE]2025-05-17 14:39:28.793	[31merror[0m	/Users/daihao/Downloads/gocode/KubeGale/utils/claims.go:48	重新写入cookie token失败,未能成功解析token,请检查请求头是否存在x-token且claims是否为规定结构
[KUBEGALE]2025-05-17 14:51:22.556	[31merror[0m	/Users/daihao/Downloads/gocode/KubeGale/api/v1/cloudCmdb/cloud_platform.go:67	创建失败!	{"error": "存在相同厂商", "errorVerbose": "存在相同厂商\nKubeGale/service/cloudCmdb.(*CloudPlatformService).CreateCloudPlatform\n\t/Users/daihao/Downloads/gocode/KubeGale/service/cloudCmdb/cloud_platform.go:108\nKubeGale/api/v1/cloudCmdb.(*CloudPlatformApi).CreateCloudPlatform\n\t/Users/daihao/Downloads/gocode/KubeGale/api/v1/cloudCmdb/cloud_platform.go:66\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/Users/daihao/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185\nKubeGale/router/cloudCmdb.(*CloudPlatformRouter).InitCloudPlatformRouter.OperationRecord.func1\n\t/Users/daihao/Downloads/gocode/KubeGale/middleware/operation.go:96\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/Users/daihao/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185\nKubeGale/initialize.Routers.CasbinHandler.func3\n\t/Users/daihao/Downloads/gocode/KubeGale/middleware/casbin_rbac.go:35\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/Users/daihao/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185\nKubeGale/initialize.Routers.JWTAuth.func2\n\t/Users/daihao/Downloads/gocode/KubeGale/middleware/jwt.go:73\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/Users/daihao/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185\ngithub.com/gin-gonic/gin.LoggerWithConfig.func1\n\t/Users/daihao/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/logger.go:249\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/Users/daihao/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185\ngithub.com/gin-gonic/gin.CustomRecoveryWithWriter.func1\n\t/Users/daihao/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/recovery.go:102\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/Users/daihao/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185\ngithub.com/gin-gonic/gin.(*Engine).handleHTTPRequest\n\t/Users/daihao/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/gin.go:633\ngithub.com/gin-gonic/gin.(*Engine).ServeHTTP\n\t/Users/daihao/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/gin.go:589\nnet/http.serverHandler.ServeHTTP\n\t/Users/daihao/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.1.darwin-arm64/src/net/http/server.go:3210\nnet/http.(*conn).serve\n\t/Users/daihao/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.1.darwin-arm64/src/net/http/server.go:2092\nruntime.goexit\n\t/Users/daihao/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.1.darwin-arm64/src/runtime/asm_arm64.s:1223"}
[KUBEGALE]2025-05-17 14:51:29.322	[31merror[0m	/Users/daihao/Downloads/gocode/KubeGale/api/v1/cloudCmdb/cloud_platform.go:67	创建失败!	{"error": "存在相同厂商", "errorVerbose": "存在相同厂商\nKubeGale/service/cloudCmdb.(*CloudPlatformService).CreateCloudPlatform\n\t/Users/daihao/Downloads/gocode/KubeGale/service/cloudCmdb/cloud_platform.go:108\nKubeGale/api/v1/cloudCmdb.(*CloudPlatformApi).CreateCloudPlatform\n\t/Users/daihao/Downloads/gocode/KubeGale/api/v1/cloudCmdb/cloud_platform.go:66\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/Users/daihao/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185\nKubeGale/router/cloudCmdb.(*CloudPlatformRouter).InitCloudPlatformRouter.OperationRecord.func1\n\t/Users/daihao/Downloads/gocode/KubeGale/middleware/operation.go:96\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/Users/daihao/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185\nKubeGale/initialize.Routers.CasbinHandler.func3\n\t/Users/daihao/Downloads/gocode/KubeGale/middleware/casbin_rbac.go:35\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/Users/daihao/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185\nKubeGale/initialize.Routers.JWTAuth.func2\n\t/Users/daihao/Downloads/gocode/KubeGale/middleware/jwt.go:73\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/Users/daihao/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185\ngithub.com/gin-gonic/gin.LoggerWithConfig.func1\n\t/Users/daihao/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/logger.go:249\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/Users/daihao/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185\ngithub.com/gin-gonic/gin.CustomRecoveryWithWriter.func1\n\t/Users/daihao/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/recovery.go:102\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/Users/daihao/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185\ngithub.com/gin-gonic/gin.(*Engine).handleHTTPRequest\n\t/Users/daihao/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/gin.go:633\ngithub.com/gin-gonic/gin.(*Engine).ServeHTTP\n\t/Users/daihao/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/gin.go:589\nnet/http.serverHandler.ServeHTTP\n\t/Users/daihao/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.1.darwin-arm64/src/net/http/server.go:3210\nnet/http.(*conn).serve\n\t/Users/daihao/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.1.darwin-arm64/src/net/http/server.go:2092\nruntime.goexit\n\t/Users/daihao/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.1.darwin-arm64/src/runtime/asm_arm64.s:1223"}
[KUBEGALE]2025-05-17 16:42:37.950	[31merror[0m	/Users/daihao/Downloads/gocode/KubeGale/api/v1/cloudCmdb/cloud_platform.go:79	修改失败!	{"error": "record not found"}
[KUBEGALE]2025-05-17 16:49:13.014	[31merror[0m	/Users/daihao/Downloads/gocode/KubeGale/api/v1/cloudCmdb/cloud_platform.go:96	删除失败!	{"error": "record not found"}
[KUBEGALE]2025-05-17 21:31:14.862	[31merror[0m	/Users/daihao/Downloads/gocode/KubeGale/core/server.go:68	accept tcp [::]:8080: use of closed network connection
[KUBEGALE]2025-05-17 21:40:53.037	[31merror[0m	/Users/daihao/Downloads/gocode/KubeGale/core/server.go:68	accept tcp [::]:8080: use of closed network connection
[KUBEGALE]2025-05-17 21:44:26.824	[31merror[0m	/Users/daihao/Downloads/gocode/KubeGale/core/server.go:68	accept tcp [::]:8080: use of closed network connection
[KUBEGALE]2025-05-17 21:48:21.435	[31merror[0m	/Users/daihao/Downloads/gocode/KubeGale/core/server.go:68	accept tcp [::]:8080: use of closed network connection
[KUBEGALE]2025-05-17 21:57:27.182	[31merror[0m	/Users/daihao/Downloads/gocode/KubeGale/core/server.go:68	accept tcp [::]:8080: use of closed network connection
[KUBEGALE]2025-05-17 22:02:16.866	[31merror[0m	/Users/daihao/Downloads/gocode/KubeGale/core/server.go:68	accept tcp [::]:8080: use of closed network connection
[KUBEGALE]2025-05-17 22:18:34.113	[31merror[0m	/Users/daihao/Downloads/gocode/KubeGale/core/server.go:68	accept tcp [::]:8080: use of closed network connection
[KUBEGALE]2025-05-17 22:37:23.940	[31merror[0m	/Users/daihao/Downloads/gocode/KubeGale/core/server.go:68	accept tcp [::]:8080: use of closed network connection
[KUBEGALE]2025-05-17 22:44:15.343	[31merror[0m	/Users/daihao/Downloads/gocode/KubeGale/core/server.go:68	net.Listen error: listen tcp :8080: bind: address already in use
